<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Paiement annulé</title>
</head>
<body>
<h1>Paiement annulé</h1>
<p>
    La commande référence {reference} a été annulée.
</p>
<p>
    Message de la part de PayBox :<br/>
</p>
<pre>{message_retour}</pre>
<p>Vous pouvez fermer cet onglet.</p>
</body>
</html>
