<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Paiement en attente</title>
  </head>
  <body>
        <h1>Paiement en attente</h1>
        <p>
                La commande référence {reference} à bien été prise en compte.
		Vous recevrez un mail une fois le paiement validé.
        </p>
	<p>
		Message de PayBox : <pre>{message_retour}</pre>
	</p>
  </body>
</html>
