<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Paiement effectué</title>
  </head>
  <body>
    <h1>Paiement effectué</h1>
    <p>
        La commande référence {reference} à bien été prise en compte.
    </p>
	<p>
		Vous recevrez un mail une fois la transaction validée.
	</p>
    <p>Vous pouvez fermer cet onglet.</p>
  </body>
</html>
