<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Paiement refuse</title>
  </head>
  <body>
        <h1>Paiement refusé</h1>
        <p>
                La commande référence {reference} a été refusé.
		Message de la banque : {message_retour}.
        </p>
        <p>» Retour vers <a href="//alforpro.vet-alfort.fr/course/view.php?id=191">AlforPro</a>.</p>
  </body>
</html>
