<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<title>Confirmation</title>
<style type="text/css">
    body {
        font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        font-size: 14px;
    }

    .info, .warning {
        border: 1px solid;
        margin: 10px 0px;
        padding: 0 10px;
        background: no-repeat 10px center;
    }

    .info {
        color: #00529B;
        background-color: #BDE5F8;
    }

    .warning {
        color: #9F6000;
        background-color: #FEEFB3;
    }

    form {
        display: block;
    }

    form label, input {
        cursor: pointer;
    }
    input {
        display: block;
        margin: 0 0 5px 0;
    }

    p.control {
        margin: 0 0 30px 0;
    }

    input[type='checkbox'] {
        display: inline-block;
    }
    .container {
        margin: auto;
        max-width: 980px;
    }
</style>
</head>
<body>
<div class="container">
    <h1>
        <img src="/view/img/alforprov5.png" alt="banner"/>
    </h1>
    <h2> *** Please confirm the following information before payment *** </h2>

    <p>
        <strong>Fee:</strong> <?= $p->getMontantEnEuro(); ?> Euro (€)<br/>
        <strong>Last name:</strong> <?= $c->getNom(); ?> <br/>
        <strong>First name:</strong> <?= $c->getPrenom(); ?> <br/>
        <strong>E-mail address:</strong> <?= $c->getEmail(); ?> <br/>
        <strong>Training session:</strong> <?= $p->getlibelle(); ?>
    </p>

    <form method="POST" action="/action.php">
        <div class="warning">
            <h3>Warning</h3>
            <p>Before paying the fees, please check the practicability of the (international) payment.</p>
        </div>
        <p class="control">
            <label>
                <input type="checkbox" required>
                I checked the practicability of the (international) payment before paying the fees.
            </label>
        </p>
        <div class="info">
            <h3>Notice</h3>
            <p>A supporting document will be requested at the time of the training session in case of payement of the
                fees for resident/intern/PhD/student.</p>
        </div>
        <p class="control">
            <label>
                <input type="checkbox" required>
                If I am eligible for a reduced fees (as a resident/intern/PhD/student), I will present a supporting
                document the first day of the Summer Class.
            </label>
        </p>
        <input name="refPayement" value="<?= $refPayement ?>" type="hidden"/>
        <input name="refClient" value="<?= $refClient ?>" type="hidden"/>
        <input value="Confirm" type="submit"/>
    </form>
    <img src="/view/img/formcoveto.jpg" alt="banner"/>
</div>
</body>
</html>
