<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<title>Confirmation</title>
<style type="text/css">
body {
	font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
	font-size: 12px;
}
</style>
</head>
<body>

<p><img src="view/img/alforprov5.png" width="500" height="89" alt="banner"/></p>
<p> *** CONFIRMATION DE VOS INFORMATIONS *** </p>
<p>Vous trouverez ci-dessous le recapitulatif de vos élément de facturation</p>

<form method="POST" action="/action.php">
	Montant : <?= $p->getMontantEnEuro(); ?>  Euro<br/>
	Nom : <?= $c->getNom(); ?> <br/>
	Prénom : <?= $c->getPrenom(); ?> <br/>
	Email : <?= $c->getEmail(); ?> <br/>
	Produit : <?= $p->getlibelle(); ?>

<p>Avant de lancer les opérations de payement, vérifier que les conditions de votre compte permettent sa réalisation (plafond et/ou approvisionnement du compte).</p>

<input name="refPayement" value="<?= $refPayement; ?>" type="hidden"/>
<input name="refClient" value="<?= $refClient ?>" type="hidden"/>

<input value="Envoyer" type="submit"/>
</form><br/>
<p><img src="view/img/formcoveto.jpg" width="500" height="92" alt="banner"/></p>
</body>
</html>
