<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Confirmation</title>
    <style type="text/css">
        body {
            font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
            font-size: 14px;
        }

        .info, .warning {
            border: 1px solid;
            margin: 10px 0px;
            padding: 0 10px;
            background: no-repeat 10px center;
        }

        .info {
            color: #00529B;
            background-color: #BDE5F8;
        }

        .warning {
            color: #9F6000;
            background-color: #FEEFB3;
        }

        form {
            display: block;
        }

        form label, input {
            cursor: pointer;
        }
        input {
            display: block;
            margin: 0 0 5px 0;
        }

        p.control {
            margin: 0 0 30px 0;
        }

        input[type='checkbox'] {
            display: inline-block;
        }
        .container {
            margin: auto;
            max-width: 980px;
        }
    </style>
</head>
<body>
<div class="container">
    <h1>
        <img src="/view/img/alforprov5.png" alt="banner"/>
    </h1>
    <h2> *** Confirmation de vos informations *** </h2>
    <p>Vous trouverez ci-dessous le recapitulatif de vos élément de facturation</p>

    <p>
        <strong>Montant :</strong> <?= $p->getMontantEnEuro(); ?> Euro (€)<br/>
        <strong>Nom :</strong> <?= $c->getNom(); ?> <br/>
        <strong>Prénom :</strong> <?= $c->getPrenom(); ?> <br/>
        <strong>Email :</strong> <?= $c->getEmail(); ?> <br/>
        <strong>Produit :</strong> <?= $p->getlibelle(); ?>
    </p>

    <form method="POST" action="/action.php">
        <div class="warning">
            <h3>Attention</h3>
            <p>Avant de lancer les opérations de payement, vérifier que les conditions de votre compte permettent sa
                réalisation
                (plafond et/ou approvisionnement du compte).</p>
        </div>
        <p class="control">
            <label>
                <input type="checkbox" required>
                J'ai vérifié que les conditions de mon compte permettent la réalisation du paiement.
            </label>
        </p>
        <div class="info">
            <h3>Information</h3>
            <p>Si vous avez opté pour le tarif résident/interne/PhD/étudiant, une pièce justificative vous sera demandée
                le
                premier jour de la formation</p>
        </div>
        <p class="control">
            <label>
                <input type="checkbox" required>
                Si je suis éligible à une réduction (en étant résident / interne / doctorant / étudiant), je présenterai
                une pièce justificative le premier jour de la session.
            </label>
        </p>
        <input name="refPayement" value="<?= $refPayement ?>" type="hidden"/>
        <input name="refClient" value="<?= $refClient ?>" type="hidden"/>
        <input value="Confirmer" type="submit"/>
    </form>
    <img src="/view/img/formcoveto.jpg" alt="banner"/>
</div>
</body>
</html>
