<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<title>Confirmation</title>
<style type="text/css">
    body {
        font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        font-size: 14px;
    }

    form {
        display: block;
    }

    input {
        display: block;
        margin: 0 0 5px 0;
    }

    .container {
        margin: auto;
        max-width: 980px;
    }
</style>
</head>
<body>
<div class="container">
    <h1>
        <img src="/view/img/alforprov5.png" alt="banner"/>
    </h1>
    <h2> *** CONFIRMATION DE VOS INFORMATIONS *** </h2>
    <p>Vous trouverez ci-dessous le recapitulatif de vos élément de facturation</p>

    <p>
        Montant : <?= $p->getMontantEnEuro(); ?> Euro<br/>
        Nom : <?= $c->getNom(); ?> <br/>
        Prénom : <?= $c->getPrenom(); ?> <br/>
        Email : <?= $c->getEmail(); ?> <br/>
        Produit : <?= $p->getlibelle(); ?>
    </p>

    <p>Avant de lancer les opérations de payement, vérifier que les conditions de votre compte permettent sa réalisation
        (plafond et/ou approvisionnement du compte).</p>

    <form method="POST" action="/action.php">
        <input name="refPayement" value="<?= $refPayement ?>" type="hidden"/>
        <input name="refClient" value="<?= $refClient ?>" type="hidden"/>
        <input value="Envoyer" type="submit"/>
    </form>
    <img src="/view/img/formcoveto.jpg" alt="banner"/>
</div>
</body>
</html>
