<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<title>Complément de données</title>
<style type="text/css">
body {
	font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
	font-size: 14px;
}
form {
    display: block;
}
input {
    display: block;
    margin: 0 0 5px 0;
}

.container {
    margin: auto;
    max-width: 980px;
}
</style>
</head>
<body>
<div class="container">
    <img src="/view/img/alforprov5.png" alt="banner"/>
    <p>Merci de compléter les informations</p>

    <form method="POST" action="/confirmation.php">
        <label for="nom">Nom : </label><input type="text" required id="nom" name="nom"/>
        <label for="prenom">Prénom : </label><input type="text" required d="prenom" name="prenom"/>
        <label for="email">Email : </label><input type="email" required id="email" name="email"/>
        <input value="Envoyer" type="submit"/>
    </form>
    <img src="/view/img/formcoveto.jpg" alt="banner"/>
</div>
</body>
</html>
