<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<title>Complément de données</title>
<style type="text/css">
body {
	font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
	font-size: 14px;
}
form {
    display: block;
}
input {
    display: block;
    margin: 0 0 5px 0;
}
</style>
</head>
<body>
<img src="view/img/banniere_Eve.png" width="500" height="89" alt="banner"/>
<p>Merci de compléter les informations</p>

<form method="POST" action="/confirmation.php">
    <label for="nom">Nom : </label><input type="text" required id="nom" name="nom"/>
    <label for="prenom">Prénom : </label><input type="text" required d="prenom" name="prenom"/>
    <label for="email">Émail : </label><input type="email" required id="email" name="email"/>
    <input type="hidden" name="persId" value="<?= uniqid();?>" />
    <input type="hidden" name="produit" value="<?= $GET['produit']?>" />
    <input value="Envoyer" type="submit"/>
</form>
<img src="view/img/banniere_fin.png" width="500" height="92" alt="banner"/>
</body>
</html>
