<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<title>Complement de données</title>
<style type="text/css">
body {
	font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
	font-size: 12px;
}
</style>
</head>
<body>

<p><img src="/view/img/alforprov5.png" width="500" height="89" alt="banner"/></p>
<p>Merci de compléter les informations</p>

<p>Vous n'avez rien à compléter</p>
<form method="POST" action="/confirmation.php">
	<input name="produit" value="<?= $GET['produit']; ?>" type="hidden"/>
	<input name="persId" value="<?= $GET['persId']; ?>" type="hidden"/>
	<input name="nom" value="<?= $GET['nom']; ?>" type="hidden"/>
	<input name="prenom" value="<?= $GET['prenom']; ?>" type="hidden"/>
	<input name="email" value="<?= $GET['email']; ?>" type="hidden"/>
<input value="Envoyer" type="submit"/>
</form><br/>
<p><img src="/view/img/formcoveto.jpg" width="500" height="92" alt="banner"/></p>
</body>
</html>
