<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<title>Complement de données</title>
<style type="text/css">
    body {
        font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        font-size: 14px;
    }

    form {
        display: block;
    }

    input {
        display: block;
        margin: 0 0 20px 0;
    }

    .container {
        margin: auto;
        max-width: 980px;
    }
</style>
</head>
<body>
<div class="container">
    <img src="/view/img/banniere.jpg" alt="banniere">
    <p>Merci de compléter les informations</p>

    <form method="POST" action="/confirmation.php">
        <input name="persId" value="<?= $GET['persId']; ?>" type="hidden"/>
        <label for="nom">Nom :</label><input required id="nom" name="nom" value="<?= $GET['nom']; ?>" type="text"/>
        <label for="prenom">Prénom :</label><input required id="prenom" name="prenom" value="<?= $GET['prenom']; ?>"
                                                   type="text"/>
        <label for="email">Email :</label><input required id="email" name="email" value="<?= $GET['email']; ?>"
                                                 type="text"/>
        <input value="Envoyer" type="submit"/>
    </form>
    <img src="/view/img/footer.jpg" alt="footer">
</div>
</body>
</html>
